### ISSUE TITLE
mAP become 0

### ISSUE THREAD

**Issue by OyamingO** [Syencil/mobile-yolov5-pruning-distillation#10]
Why did mAP all become 0 after the second epoch when I used mobilev2-yolo5s to train my data?

**Comment by Syencil** [comment]
be careful of overfitting

**Comment by OyamingO** [comment]
你好，为什么同样的数据集，同样的参数在yolov5s上没有过拟合呢？我还需要调整什么参数吗？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Syencil/mobile-yolov5-pruning-distillation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上6:38
收件人:&nbsp;"Syencil/mobile-yolov5-pruning-distillation"<mobile-yolov5-pruning-distillation@noreply.github.com&gt;;
抄送:&nbsp;"O亚明O"<1964533558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Syencil/mobile-yolov5-pruning-distillation] mAP become 0 (#10)





 
be careful of overfitting

**Comment by Syencil** [comment]
1. yolov5s大概率你用了官方的coco权重，mobile没有。可以尝试yolov5s train from scratch或者将mobile版本在coco或者voc这种数据集上做pre-train。
2. 你自己的数据集太小了或者train/val分布不均匀。

**Comment by OyamingO** [comment]
好的，非常感谢，我再做一下实验




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Syencil/mobile-yolov5-pruning-distillation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 上午10:52
收件人:&nbsp;"Syencil/mobile-yolov5-pruning-distillation"<mobile-yolov5-pruning-distillation@noreply.github.com&gt;;
抄送:&nbsp;"O亚明O"<1964533558@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Syencil/mobile-yolov5-pruning-distillation] mAP become 0 (#10)





  
yolov5s大概率你用了官方的coco权重，mobile没有。可以尝试yolov5s train from scratch或者将mobile版本在coco或者voc这种数据集上做pre-train。
 
你自己的数据集太小了或者train/val分布不均匀。

**Comment by BVVega** [comment]
![image](https://user-images.githubusercontent.com/39092556/113134729-c29de280-9253-11eb-9fdb-3d92d740cb2d.png)
相同的问题,我大概找了mobilenetv2的在coco上的预训练模型在mobile-yolov5s上进行finetune,为何我的map也是趋近于0,而且是越来越下降,cls=1,traindata_num=2w.请问这是什么原因呢

**Comment by Syencil** [comment]
参考 #38
