### ISSUE TITLE
after  pruning，how can get the new yaml

### ISSUE THREAD

**Issue by mathpopo** [Syencil/mobile-yolov5-pruning-distillation#11]
first very thank you for your job
i just use pruning.py ,at last save just save a whole new model ,how can i get the new yaml.could teach me?

**Comment by Syencil** [comment]
new model can not just be saved in this ez format. and its unnecessary.

**Comment by mathpopo** [comment]
if want to continue to pruning to more small,should need to get new yaml to first finetune it ?

**Comment by Syencil** [comment]
opt.weight = your model path

**Comment by mathpopo** [comment]
@Syencil  you mean,continue train on the base of _mobilenet_v2-b0353104.pth && mobile-yolo5s_voc.yaml?
i mean pruning 3 1.87   could i contine to reduce 1.87 ? so i ask for the yml point to the new pruning model

**Comment by Syencil** [comment]
opt.finetune does not need yaml file. u can restore the model from pth instead of yaml file.

**Comment by mathpopo** [comment]
@Syencil if no yaml. how can build_model,if no model,how can load new pruning model pth?
