### ISSUE TITLE
mobile-yolo5s.yaml 该文件中 detect layer  是空的？

### ISSUE THREAD

**Issue by EricHuiK** [Syencil/mobile-yolov5-pruning-distillation#16]

**Comment by Syencil** [comment]
哪里？

**Comment by EricHuiK** [comment]
![image](https://user-images.githubusercontent.com/35529046/102845366-618e9380-4448-11eb-8b1b-b8a19d31b010.png)

**Comment by EricHuiK** [comment]
yolov5s_voc.yaml  里面的detect层

**Comment by EricHuiK** [comment]
[[], 1, Detect, [nc, anchors]],

**Comment by Syencil** [comment]
直接看源码吧 有默认的
