### ISSUE TITLE
Pruning 段错误

### ISSUE THREAD

**Issue by dengly** [Syencil/mobile-yolov5-pruning-distillation#18]
我先是通过 `python train.py --type mvocs` 进行训练，再通过`python3 train.py --type smvocs`将上一步的best_mvocs.pt作为本次训练的输入模型，再通过`python3 pruning.py -t 0.1`将上一步的best_smvocs.pt作为本次的输入模型，运行`python3 pruning.py -t 0.1`就报`段错误`

**Comment by dengly** [comment]
`python train.py --type mvocs` 的 epochs是300
`python train.py --type smvocs` 的 epochs是100

**Comment by Syencil** [comment]
这描述给的信息太少了 尝试单步debug吧 我这边流程是没问题

**Comment by dengly** [comment]
> 这描述给的信息太少了 尝试单步debug吧 我这边流程是没问题

确认一下我这样的操作是否正常

**Comment by dengly** [comment]
这个是我执行的脚步
```
# 训练 Baseline
python train.py --type mvocs

# 稀疏 sparse learning
python3 train.py --type smvocs

# 剪枝 Pruning
python3 pruning.py -t 0.1

# 微调 finetune
python3 train.py --type fsmvocs

# 蒸馏 Distillation
python3 train.py --type dmvocs

```

**Comment by dengly** [comment]
我修改了 cfg、data、weights、epochs、batch_size

**Comment by dengly** [comment]
baseline用的模型是 mobilenet_v2-b0353104.pth，后续的都是上一次训练得到的best模型，到pruning这步就这样了。我尝试重新训练看看是否正常

**Comment by TongShuo-Demon** [comment]
> 这个是我执行的脚步
> 
> ```
> # 训练 Baseline
> python train.py --type mvocs
> 
> # 稀疏 sparse learning
> python3 train.py --type smvocs
> 
> # 剪枝 Pruning
> python3 pruning.py -t 0.1
> 
> # 微调 finetune
> python3 train.py --type fsmvocs
> 
> # 蒸馏 Distillation
> python3 train.py --type dmvocs
> ```
能问问您关于这个数据集放置的问题吗

**Comment by Syencil** [comment]
走debug吧 看是哪个位置错了

**Comment by dengly** [comment]
我使用IDEA运行正常，命令行运行报错

**Comment by dengly** [comment]
定位的执行bn_analyze方法的`plt.hist(bn_val, bins=101, align="mid", log=True, range=(0, 1.0))`报错

**Comment by Syencil** [comment]
如果是服务器terminal应该不带显示功能吧 plt的问题

**Comment by dengly** [comment]
定位到是matplotlib.pyplot相关方法调用报错，我注掉后使用IDEA运行正常，但是通过终端执行还是会报段错误。

**Comment by dengly** [comment]
> 如果是服务器terminal应该不带显示功能吧 plt的问题

我用的是深度的系统，deepin v20

**Comment by TongShuo-Demon** [comment]
test.py文件使用剪枝后的模型会报错，报错信息如下：
Traceback (most recent call last):
  File "/home/demon/PycharmProjects/mobile-yolov5-pruning-distillation/test.py", line 357, in <module>
    test(opt.data,
  File "/home/demon/PycharmProjects/mobile-yolov5-pruning-distillation/test.py", line 89, in test
    names = {k: v for k, v in enumerate(model.names if hasattr(model, 'names') else model.module.names)}
  File "/home/demon/anaconda3/envs/pytorch_gpu/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Model' object has no attribute 'module'
