### ISSUE TITLE
 "render_img/before_pruning.jpg"

### ISSUE THREAD

**Issue by CBIR-LL** [Syencil/mobile-yolov5-pruning-distillation#2]
Thank you for sharing the code. When I run the pruning operation, there is a missing image. Can you provide me with this picture？

**Comment by Syencil** [comment]
it doesnt need any pic. its just generated by the codes!

**Comment by CBIR-LL** [comment]
Yes, you are right. I forgot to create the folder manually in advance. Thank you for your advice.
