### ISSUE TITLE
mobilenet作为骨干网络,采用mobilenet的权重文件收敛速度变得很慢

### ISSUE THREAD

**Issue by TongShuo-Demon** [Syencil/mobile-yolov5-pruning-distillation#25]
我在yolov5最新的工程文件上采用mobilenet作为骨干网络,此外采用mobilenet的权重文件收敛速度变得很慢,但是我直接跑作者的代码却收敛的很快,我能问问大概是什么原因吗?

**Comment by Syencil** [comment]
yolov5提供的预训练权重backbone+head都是在coco上训练好的，你只需要finetune最后一层而已。我这个换了mobilenet之后，backbone仅仅只是在imagenet上做的pretrain，head则是初始化，相当于从头训练。你可以尝试不加载yolov5预训练权重试试

**Comment by TongShuo-Demon** [comment]
> yolov5提供的预训练权重backbone+head都是在coco上训练好的，你只需要finetune最后一层而已。我这个换了mobilenet之后，backbone仅仅只是在imagenet上做的pretrain，head则是初始化，相当于从头训练。你可以尝试不加载yolov5预训练权重试试

非常感谢您,但是现在我发现新的问题,那就是我的P、R、map等数据低了很多

**Comment by Syencil** [comment]
这种很正常 可以分别从数据量和capacity这两个方面入手提升

**Comment by TongShuo-Demon** [comment]
> 这种很正常 可以分别从数据量和capacity这两个方面入手提升

再次感谢您！我换成coco数据集确实效果明显不一样了。再次麻烦你，请问剪枝使用的方法是network slimming这篇论文的方法吗

**Comment by Syencil** [comment]
https://arxiv.org/pdf/1708.06519.pdf

**Comment by TongShuo-Demon** [comment]
> https://arxiv.org/pdf/1708.065

**Comment by TongShuo-Demon** [comment]
> https://arxiv.org/pdf/1708.06519.pdf

非常感谢
