### ISSUE TITLE
About pretrained weight

### ISSUE THREAD

**Issue by WuPedin** [Syencil/mobile-yolov5-pruning-distillation#27]
Hi 
Could you share your pretrained weight?
(mobilenet_v2-b0353104.pth)

When I download the weights, it turns that this folder is in your google drive trash can.
https://drive.google.com/drive/folders/1Drs_Aiu7xx6S-ix95f9kNsA6ueKRpN2J

Thank you.

**Comment by Syencil** [comment]
where u got this link? i will check it soon

**Comment by WuPedin** [comment]
Hi Syencil,

I got this link from google_utils.py.
![image](https://user-images.githubusercontent.com/31273808/106250368-7ed82e00-624e-11eb-9bde-6f91ebc0c42f.png)

Thanks for your attentions!

**Comment by noobimp** [comment]
我训练时也遇到了权重文件无法下载的问题，看起来是原来版本的权重文件被从网盘中删掉了……请问还有有效链接吗

**Comment by swuxyj** [comment]
试试这个
https://github.com/mihir135/yolov5/issues/3#issuecomment-651553649

**Comment by younghuvee** [comment]
> 我训练时也遇到了权重文件无法下载的问题，看起来是原来版本的权重文件被从网盘中删掉了……请问还有有效链接吗

https://github.com/pytorch/vision/tree/master/torchvision/models

**Comment by Syencil** [comment]
参考 #38
