### ISSUE TITLE
关于蒸馏的一些问题

### ISSUE THREAD

**Issue by tangchen2** [Syencil/mobile-yolov5-pruning-distillation#28]
感谢作者的repo，真的学到了很多，在看蒸馏实验室遇到了一些疑惑想和作者请教一下
1. Strategy1 Output Based Distillation，repo中关于Teacher部分的蒸馏损失全都是用MSELoss计算的，而论文中仍然采用和原始YOLO相同的Loss，会不会这一块限制Student网络的调优
2. Strategy2 Feature Based + Output Based Distillation，repo中似乎是通过参数控制一起训练的，而论文中是先冻结Feature Map之后的参数进行Feature Distillation，然后再解冻进行全局Distillation，会不会这部分限制了Strategy2的效果导致最后mAP偏低；且论文里Convert应该只有卷积，没有加上BN和Relu两个操作

**Comment by Syencil** [comment]
1.outputbased仍然用的原loss形式，MSE是TS之间的知识迁移，换CE什么的都可以不过意义不大。
2.论文没有细看，不过先冻结的话得先训练好TS之后再蒸馏？那样的话意义不太大把。BN+RELU加不加我都试过了，对于检测任务而言feature-based效果并不好，至少是在这个yolo项目上是的
