### ISSUE TITLE
关于权重文件下载问题

### ISSUE THREAD

**Issue by noobimp** [Syencil/mobile-yolov5-pruning-distillation#31]
当我执行前两个训练命令时，出现了以下错误，剩余的训练命令也类似，请问怎么解决呢qaq
![QQ截图20210306102921](https://user-images.githubusercontent.com/50991169/110192125-36241e00-7e67-11eb-98d0-68bdaf3e3cdc.png)
![QQ截图20210306102941](https://user-images.githubusercontent.com/50991169/110192128-391f0e80-7e67-11eb-9d74-51885704a44d.png)

**Comment by younghuvee** [comment]
把权重下下来 放到一个路径下，然后在配置文件yolov5s.yaml里面改一下权重路径。

**Comment by noobimp** [comment]
> 把权重下下来 放到一个路径下，然后在配置文件yolov5s.yaml里面改一下权重路径。

现在下载的pt文件是v4.0的了，和作者用的yolov5版本不匹配，旧版本的也没找到（哭

**Comment by Syencil** [comment]
参考 #38

**Comment by ahhhxxx** [comment]
> > 把权重下下来 放到一个路径下，然后在配置文件yolov5s.yaml里面改一下权重路径。
> 
> 现在下载的pt文件是v4.0的了，和作者用的yolov5版本不匹配，旧版本的也没找到（哭

你找到权重文件了吗？

**Comment by songjiahao-wq** [comment]
请问mobilenet_v2-b0353104.pth文件如何添加
