### ISSUE TITLE
蒸馏时Precision下降太多的问题

### ISSUE THREAD

**Issue by CangHaiQingYue** [Syencil/mobile-yolov5-pruning-distillation#34]
感谢大佬的工程。
我在蒸馏时，发现Precision下降挺多的，看到您的几个蒸馏方案中，也是Precision比没有蒸馏前低一些，这个问题可以通过啥方法改善么？
单分类的，倒是没什么大的下降~

**Comment by Syencil** [comment]
map上升了啊 你要P的话就把阈值提高 R降低

**Comment by Syencil** [comment]
参考 #38
