### ISSUE TITLE
all processes

### ISSUE THREAD

**Issue by eeric** [Syencil/mobile-yolov5-pruning-distillation#6]
your work as following:
sparse learning-->prune-->finetune-->distill ?

**Comment by Syencil** [comment]
yeah. if it helps u, plz click star :)

**Comment by eeric** [comment]
ok

**Comment by mathpopo** [comment]
@Syencil   could offer the train data?

**Comment by Syencil** [comment]
> @Syencil could offer the train data?

refer in readme
