### ISSUE TITLE
大佬好，注意到 yolo head 和原版的有所不同，想问下具体做了哪些改变 

### ISSUE THREAD

**Issue by Veal98** [Syencil/mobile-yolov5-pruning-distillation#65]
如题，感谢大佬回复！

**Comment by Syencil** [comment]
用的他们之前版本的head，更轻一些

**Comment by Veal98** [comment]
> 用的他们之前版本的head，更轻一些

大佬，看了一下 1.0 和 2.0 版本的 head，好像都我们这个项目还是不一样诶

**Comment by Syencil** [comment]
用的中间的一个版本 后来他们就改了 目前应该绝版了 不过参数量和Flop都非常低 可以改成你想要的就行了

**Comment by Veal98** [comment]
> 用的中间的一个版本 后来他们就改了 目前应该绝版了 不过参数量和Flop都非常低 可以改成你想要的就行了

好嘞，感谢大佬！
