### ISSUE TITLE
why baseline model not use yolov5s-5x from ultralytics / yolov5

### ISSUE THREAD

**Issue by eeric** [Syencil/mobile-yolov5-pruning-distillation#7]
problem as above.
your code about yolo.py was  inconsistent with ultralytics / yolov5
it was occur error that Detect has no 'export'.

**Comment by Qingyuncookie** [comment]
Hey,  have you solved this problem, I had the same problem

**Comment by Qingyuncookie** [comment]
Hey, have you solved this problem, I had the same

**Comment by eeric** [comment]
@Qingyuncookie 
no, and I was not used this project.
