### ISSUE TITLE
voc data question

### ISSUE THREAD

**Issue by mathpopo** [Syencil/mobile-yolov5-pruning-distillation#8]
voc_train.txt
voc_test.txt
where can get them?

**Comment by mathpopo** [comment]
https://awesomeopensource.com/project/YunYang1994/tensorflow-yolov3

**Comment by Syencil** [comment]
mobile-yolov5-pruning-distillation/script/voc_label.py

**Comment by mathpopo** [comment]
@Syencil  ok  thansk，但是我设置了多卡训练会报错，设置单卡就没问题

**Comment by Syencil** [comment]
yolov5 2.0的问题 不知道3.0他们改了没有
