### ISSUE TITLE
it was biger to yolov5s model pruned

### ISSUE THREAD

**Issue by eeric** [Syencil/mobile-yolov5-pruning-distillation#9]
it existed error to your pruned code.

**Comment by Syencil** [comment]
i would be appreciated it if u could paste ur code and show me where goes wrong

**Comment by eeric** [comment]
pruning 14.48M yolov5s.pt, turned to 17. 59M best_fsmvocs.pt, when t=0.8
if t=0.1, size of best_fsmvocs.pt to biger.

**Comment by Syencil** [comment]
pt size does not mean anything about actual model size. u should figure it out the whole pipline and try to debug if there were something wrong. btw, this method is not network-slimming. plz refer the original paper.

**Comment by eeric** [comment]
really，your means was different with network-slimming.
